# Generated by Django 4.2.4 on 2023-08-12 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NearEarthObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('neo_reference_id', models.CharField()),
                ('name', models.CharField()),
                ('absolute_magnitude_h', models.FloatField()),
                ('is_potentially_hazardous_asteroid', models.BooleanField()),
            ],
        ),
    ]
