# Generated by Django 4.2.4 on 2023-08-12 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nasa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_result', models.TextField()),
            ],
        ),
    ]
